
spring:
  application:
    name: moneymanager

  datasource:
    url: jdbc:postgresql://localhost:5432/moneymanager-db
    username: myuser
    password: mypassword

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword

  data:
    mongodb:
      host: localhost
      port: 27017
      database: moneymanager
      username: myuser
      password: mypassword
      authentication-database: admin